### ISSUE TITLE
Крашится на странице контроля групп

### ISSUE THREAD

**Issue by locsor** [KotikMatmexa/TimeTableAnalytics#14]
TypeError: Cannot read property 'groups' of undefined
getData
C:/Users/User/Downloads/36B/TimeTableAnalytics/Frontend/src/reducer/groupReducer.js:34
  31 |    // console.log(faculty)
  32 |     let obj = Object.values(table_example).find(item => item.faculty == faculty);
  33 |     //console.log(obj)
> 34 |     let index = Object.values(obj.groups).findIndex(it => it.name == group);
  35 |     //console.log(index)
  36 |     return obj.groups[index].data;
  37 | };

groupReducer
C:/Users/User/Downloads/36B/TimeTableAnalytics/Frontend/src/reducer/groupReducer.js:24
  21 | 
  22 |    switch (action.type){
  23 |        case "LOAD_GROUP_DATA":
> 24 |            return getData(action.faculty,action.group);
     | ^  25 |        default:
  26 |            return state;
  27 |    }

setActiveGroup
C:/Users/User/Downloads/36B/TimeTableAnalytics/Frontend/src/Containers/FilterDataContainer.js:179
  176 |    },
  177 | 
  178 |    setActiveGroup:(faculty,group) => {
> 179 |        dispatch(setActiveGroup(faculty, group))
      | ^  180 |    },
  181 | 
  182 |    loadTeachersList: (address) => {

GroupFilterComponent.loadData
C:/Users/User/Downloads/36B/TimeTableAnalytics/Frontend/src/Components/FilterComponent/groupFilter.js:36
  33 | 
  34 | 
  35 |        this.props.loadData(true);
> 36 |        this.props.setActiveGroup(faculty, group);
     | ^  37 |    };
  38 | 
  39 |

**Comment by locsor** [comment]
Для репродукции выберите любую группу из любого факультета и перейдите в другую категорию. Потом вернитесь на страницу контроля групп и выберете группу не выбирая факультет.

**Comment by Snezzz** [comment]
Fixed
