### ISSUE TITLE
Выбор стека технологий

### ISSUE THREAD

**Issue by KotikMatmexa** [KotikMatmexa/TimeTableAnalytics#2]
- [x] Рассмотреть работы прошлых лет
https://github.com/sergere15/analysis_of_SPBU_timetable
https://github.com/spbu-schedule

- [x] Предложить общие варианты реализации проекта, не учитывая конкретных задач, исходя из базовых требований таких как загруженность аудиторий, преподавателей, статистика по факультетам. 
Реализация может быть сделана как с нуля (Python Flask, Django и т.д.), с использованием готовых стаков (ELK, Graylog и т.д.) и других вариантов, идеи прошу в комментарии к этому issue

**Comment by Snezzz** [comment]
Хочу предложить в качестве варианта следующий шаблон проекта с соответствующим стеком технологий.
Проект состоит из двух частей: frontend и backend. Frontend отвечает за взаимодействие с аналитиком (пользователем): получение запросов от пользователя и формирование из них запросов к серверу. Здесь я предлагаю использовать React + Reduce, так как имею в этом навыки и смогу достаточно быстро реализовывать необходимые компоненты приложения. Backend отвечает за обработку запросов со стороны frontend'а. Он работает с базой данных, предоставляет все необходимые результаты за оптимальный промежуток времени. Здесь можно было бы использовать как Python Flask, так и Spring (Java). 
Данный вариант проекта я считаю наиболее оптимальным, так как здесь присутствует независимость частей, а значит уже сейчас можно каждому участнику команды приступать к своей основной задаче - создание соответствующих компонентов, что ускорит процесс в дальнейшем. Идея: делаем скелет проекта, затем наполняем его необходимыми компонентами.
Рада буду принять любые комментарии/пожелания/дополнения к моей идее.

**Comment by AnastasiaBerlina** [comment]
Согласна с предложением по стеку выше. Как бэкенд разработчик могу сказать, что мне было бы удобнее и привычнее работать с Java Spring и бд PostgreSQL (тут не критично), но для начала разработки и проектирования скелета приложения необходимо увидеть уже существующую структуру данных, чтобы иметь представление в каком направлении двигаться.
Пока доступа к данным нет, чтобы не терять время, можно было бы подумать над макетами для разбивки помещений по факультетам (как это будет выглядеть и тд), так как эта проблема была озвучена одной из первых.

**Comment by Snezzz** [comment]
Считаю важным, что для создания макета необходимо обсудить некоторые моменты, связанные с предыдущими работами, с диспетчером.

**Comment by KotikMatmexa** [comment]
После обсуждения общая модель архитектуры (web-приложение, серверная часть, самостоятлеьная реализация компонетнтов) остается неизменной.
