### ISSUE TITLE
Работа с базой данных

### ISSUE THREAD

**Issue by KotikMatmexa** [KotikMatmexa/TimeTableAnalytics#3]
- [x] Получить текущую базу данных
- [x] Развернуть базу
- [x] Описать структуру
- [ ] Расмотреть варианты оптимизации запросов к базе данных для составления форм 
Кеш, снижающий нагрузку на первоисточник

**Comment by KotikMatmexa** [comment]
Получено руководство и файлы для равертывания бд локально (доступно в файлах msteams)

**Comment by AnastasiaBerlina** [comment]
Была восстановлена база данных из полученного бэкапа, в развернутом виде её размер составляет внушительные 79ГБ.
Сама бд состоит из 131 таблицы со сложной структурой связей между ними.

В ходе первоначального анализа базы был выявлен ряд проблем, касающийся как данных, содержащихся в таблицах, так и  самих таблиц.

- "Битые" данные в текстовых полях на русском и английском языках, пропущенны буквы от чего текст нечитаем (например в таблицах (EducatorEmployment, EducatorMasterPerson, EducatorPerson и т.д.) Неясно, является ли это последствием бэкапа/восстановления или же данные хранятся в оригинальной базе в таком виде.

- Необновляемые таблицы. Например, Holiday, последние данные в которой датируются 2016 годом.

- Пустые таблицы ( UserApplicationStatus, UserApplicationUpdate, UserApplication и тд).

- Неструктурированная информация. К примеру, в LocationClassrooms_ClassroomAccessKindClassroomAccessKinds в поле additional Info в текстовых полях лежит информация о техническом оснащении помещений ( "на 6-8 человек, 6 компьютеров, без проектора", "Проектор, экран, ПК, микрофоны, камера, видеоконференцсвязь"). Если мы хотим иметь возможность анализа оборудования по аудиториям (что было выяснено в ходе разговора с заказчиком), то необходимо будет реструктурировать эти данные.

- Есть странные таблицы в которых содержаться только oid (UserStudyPlan,UserRole )
