### ISSUE TITLE
Формирование макетов и их описание

### ISSUE THREAD

**Issue by Snezzz** [KotikMatmexa/TimeTableAnalytics#4]
- [x] Пересмотреть видео по первой встрече с заказчиком, обратить внимание на нюансы
- [x] Продумать возможные варианты решения возникших проблем
- [x] Сформировать шаблонные макеты SPA
- [x] Описать функциональные возможности по каждому из макетов
- [x] Обсудить текущую идею с тимлидом/с командой
- [x] Обсудить текущую идею с заказчиком
- [x] Обсудить текущую идею с диспетчером
- [x] Модифицировать макеты в дальнейшем

**Comment by KotikMatmexa** [comment]
Получена обратная свзяь, указаны некоторые недосттаки макетов:
* Число мест в аудиториях не брать в качестве выборки, достаточно укзаывать рядом с номером аудиторий
* Вид макета должен быть приближен к формату с которым привыкли работаь диспетчеры (пример в чате в msteams)
* Три основных задачи: занятость по факультетам, занятость по аудиториям и проверка соответсвия расписания учебным программам

**Comment by Snezzz** [comment]
Была проведена модификация макета проекта по результатам встречи с диспетчером.

1.Занятость аудиторий определяется не по конкретным факультетам, а по адресам. Наводя мышкой на адрес, пользователь может увидеть список всех факультетов(кафедр), что относятся к данному зданию.
2.Были внесены изменения в период. Так как на одном факультете может быть назначено разное время начала пары, было решено отображать в результате загруженности конкретный промежуток времени. В случае если кабинет полностью свободен на выбранный промежуток, выводится текстовая строка. В поле отображается только те пары, когда кабинет занят
3.Количество мест в аудитории теперь отображается просто как информация рядом с номером кабинета
4.В занятости преподавателя теперь все устроено таким образом: выбираются адреса зданий, отображаются преподаватели всех факультетов, при нажатии на кнопку "Посмотреть занятость" отображается расписание выбранного преподавателя конкретно для выбранных зданий по адресам. Во вспомогательной панели отображается адрес здания, в котором проходит выбранная пара. 

"Вид макета должен быть приближен к формату с которым привыкли работать диспетчеры", "проверка соответствия расписания учебным программам" - здесь мне требуется помощь в понимании со стороны тимлида.

Исправленный макет:
https://www.figma.com/file/txBnLv3gvSRwNh31L7qPNh/analysis_of_SPBU_timetable?node-id=1%3A10,
https://www.figma.com/file/txBnLv3gvSRwNh31L7qPNh/analysis_of_SPBU_timetable?node-id=2%3A30

**Comment by Snezzz** [comment]
При окончании диалога с тимлидом был создан макет по разделу "проверка соответствия расписания учебным программам". В данном разделе выбирается факультет, после чего для выбора конкретной группы предоставляется список групп данного факультета. В результате формируется таблица, где указана дисциплина, количество назначенных часов(по расписанию), количество требуемых часов (по ученой программе) и количество требуемых для добавления в расписание часов (остаток).

Следующий шаг - обсуждение макетов с заказчиком 

Новый макет:
https://www.figma.com/file/txBnLv3gvSRwNh31L7qPNh/analysis_of_SPBU_timetable?node-id=20%3A2
