### ISSUE TITLE
Запросы к базе данных

### ISSUE THREAD

**Issue by KotikMatmexa** [KotikMatmexa/TimeTableAnalytics#8]
Первые необходимые запросы
- [x] Зная адреса зданий (список) и рассматриваемый перид (даты начала и конца) получить аудитории для здания и расписание занятий для каждой из них
- [x] Зная адреса зданий получить список преподавателей
- [x] Зная преподавателей из второго пункта, даты начала и конца получить список пар этого преподавателя
- [x] Зная факультет и группу получить список предметов и количество пар по ним на текущий момент и если в базе есть информация то суммарное число пар по программе

**Comment by Snezzz** [comment]
- [x] Предоставить мне шаблон структуры JSON, в котором будут отправляться данные по каждому из пунктов выше

**Comment by AnastasiaBerlina** [comment]
Рализован запрос 1. 
Так же в приложении появился сваггер, чтобы не перекидываться в гите json-ами, там можно посмотреть какой запрос, какие параметры ожидаются и какой json возвращается, он при поднятии приложения по этому адресу:
http://localhost:8080/swagger-ui.html

приложение без развернутой базы не поднимется (на всякий), но если есть необходимость поднять только для сваггера,  напишите мне

**Comment by AnastasiaBerlina** [comment]
Примеры ответов на запрос 1 и сопуствующий по фильтру всех имеющихся зданий по имени
[все пары по адресу (жирный запрос).txt](https://github.com/KotikMatmexa/TimeTableAnalytics/files/5544963/default.txt)
[всее пары по адресу 2.txt](https://github.com/KotikMatmexa/TimeTableAnalytics/files/5544966/2.txt)
[все пары по адресу 1.txt](https://github.com/KotikMatmexa/TimeTableAnalytics/files/5544967/1.txt)
[поиск по имени.txt](https://github.com/KotikMatmexa/TimeTableAnalytics/files/5544968/default.txt)

**Comment by Snezzz** [comment]
В ходе тестирования реальных данных по этим документам была проведена программная модификация отображения данных и обнаружены следующие моменты:
1.Нет данных о факультетах, которые располагаются по данному адресу. Это необходимо для дополнительного информирования при наведении на адрес. Здесь было бы лучше сделать отдельный запрос, где помимо данных об адресе есть и данные о том, какие факультеты (только названия можно) располагаются по данному адресу.
2.В поле "events" пары текущей аудитории располагаются в произвольном порядке. Было бы лучше, чтобы они располагались по возрастанию дат. Это необходимо для того, чтобы я в дальнейшем смогла реализовать функцию по разбиению поля "events" на несколько дней по датам.
3.В ходе работы с реальными данными заметила, что есть вместимость кабинета (capacity) = 0. Хотелось бы узнать, по какой причине там такое значение.
4.Были замечены данные, в которых одна и та же пара с одним и тем же временем повторяется несколько раз. Отличие там только в поле "display_text" - зачем нам это? Думаю, что этот момент нужно пофиксить.

Что касается поиска адреса по имени, данную функцию я могу реализовать в дальнейшем как дополнение.

**Comment by AnastasiaBerlina** [comment]
Пункт 2 done

**Comment by AnastasiaBerlina** [comment]
как и просили  пофикшенный запрос с сортировкой и отдельный запрос на адреса со зданиями разными голосами

[все адреса.txt](https://github.com/KotikMatmexa/TimeTableAnalytics/files/5559850/default.txt)
[пофикшена сортировка.txt](https://github.com/KotikMatmexa/TimeTableAnalytics/files/5559851/default.txt)

**Comment by AnastasiaBerlina** [comment]
Найти всех преподавателей по адресу : готово
Но думаю, нужно конкретизировать запрос, потому что пока возвращаются преподаватели которые когда либо в этом здании вели пары

**Comment by AnastasiaBerlina** [comment]
Найти все пары у конкретного преподавателя - готово
[все пары у преподавателя.txt](https://github.com/KotikMatmexa/TimeTableAnalytics/files/5586100/default.txt)

Так же везде, где возможно, к парам добавлены факультет и группа у которой она проводится (иногда в базе нет этих значений)
 У преподавателей добавлено поле position: звание
